In [ ]:
import pandas as pd
import numpy as np
import statsmodels.api as sm

In [ ]:
data = pd.read_csv("USA_Housing.csv")

In [ ]:
data.head()

Avg. Area Income  ...                                            Address
0      79545.458574  ...  208 Michael Ferry Apt. 674\nLaurabury, NE 3701...
1      79248.642455  ...  188 Johnson Views Suite 079\nLake Kathleen, CA...
2      61287.067179  ...  9127 Elizabeth Stravenue\nDanieltown, WI 06482...
3      63345.240046  ...                          USS Barnett\nFPO AP 44820
4      59982.197226  ...                         USNS Raymond\nFPO AE 09386

[5 rows x 7 columns]

In [ ]:
data.drop('Address',axis = 1,inplace = True)

In [ ]:
data.head()

Avg. Area Income  Avg. Area House Age  ...  Area Population         Price
0      79545.458574             5.682861  ...     23086.800503  1.059034e+06
1      79248.642455             6.002900  ...     40173.072174  1.505891e+06
2      61287.067179             5.865890  ...     36882.159400  1.058988e+06
3      63345.240046             7.188236  ...     34310.242831  1.260617e+06
4      59982.197226             5.040555  ...     26354.109472  6.309435e+05

[5 rows x 6 columns]

In [ ]:
data.columns = ['avg_income','avg_house_age','avg_number_rooms','avg_number_bedrooms','area_population','price']
data

avg_income  avg_house_age  ...  area_population         price
0     79545.458574       5.682861  ...     23086.800503  1.059034e+06
1     79248.642455       6.002900  ...     40173.072174  1.505891e+06
2     61287.067179       5.865890  ...     36882.159400  1.058988e+06
3     63345.240046       7.188236  ...     34310.242831  1.260617e+06
4     59982.197226       5.040555  ...     26354.109472  6.309435e+05
...            ...            ...  ...              ...           ...
4995  60567.944140       7.830362  ...     22837.361035  1.060194e+06
4996  78491.275435       6.999135  ...     25616.115489  1.482618e+06
4997  63390.686886       7.250591  ...     33266.145490  1.030730e+06
4998  68001.331235       5.534388  ...     42625.620156  1.198657e+06
4999  65510.581804       5.992305  ...     46501.283803  1.298950e+06

[5000 rows x 6 columns]

In [ ]:
x_train = data[['avg_income','avg_house_age','avg_number_rooms','avg_number_bedrooms','area_population']]

In [ ]:
x_train.head()

avg_income  avg_house_age  ...  avg_number_bedrooms  area_population
0  79545.458574       5.682861  ...                 4.09     23086.800503
1  79248.642455       6.002900  ...                 3.09     40173.072174
2  61287.067179       5.865890  ...                 5.13     36882.159400
3  63345.240046       7.188236  ...                 3.26     34310.242831
4  59982.197226       5.040555  ...                 4.23     26354.109472

[5 rows x 5 columns]

In [ ]:
y_train = data['price']

In [ ]:
y_train.head()

0    1.059034e+06
1    1.505891e+06
2    1.058988e+06
3    1.260617e+06
4    6.309435e+05
Name: price, dtype: float64

In [ ]:
X = np.asarray(x_train,dtype = float)

In [ ]:
Y = np.asarray(y_train,dtype = float)

In [ ]:
X = sm.add_constant(X)

In [ ]:
X

array([[1.00000000e+00, 7.95454586e+04, 5.68286132e+00, 7.00918814e+00,
        4.09000000e+00, 2.30868005e+04],
       [1.00000000e+00, 7.92486425e+04, 6.00289981e+00, 6.73082102e+00,
        3.09000000e+00, 4.01730722e+04],
       [1.00000000e+00, 6.12870672e+04, 5.86588984e+00, 8.51272743e+00,
        5.13000000e+00, 3.68821594e+04],
       ...,
       [1.00000000e+00, 6.33906869e+04, 7.25059061e+00, 4.80508098e+00,
        2.13000000e+00, 3.32661455e+04],
       [1.00000000e+00, 6.80013312e+04, 5.53438842e+00, 7.13014386e+00,
        5.44000000e+00, 4.26256202e+04],
       [1.00000000e+00, 6.55105818e+04, 5.99230531e+00, 6.79233610e+00,
        4.07000000e+00, 4.65012838e+04]])

In [ ]:
Y

array([1059033.55787012, 1505890.91484695, 1058987.98787608, ...,
       1030729.58315229, 1198656.87240769, 1298950.48026696])

In [ ]:
model = sm.OLS(Y,X)

In [ ]:
results = model.fit()

In [ ]:
results.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.918
Model:                            OLS   Adj. R-squared:                  0.918
Method:                 Least Squares   F-statistic:                 1.119e+04
Date:                Mon, 13 Dec 2021   Prob (F-statistic):               0.00
Time:                        13:05:20   Log-Likelihood:                -64714.
No. Observations:                5000   AIC:                         1.294e+05
Df Residuals:                    4994   BIC:                         1.295e+05
Df Model:                           5                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const      -2.637e+06   1.72e+04   -153.708      0.000   -2.67e+06    -2.6e+06
x1            21.5780      0.134    160.656      0.000      21.315      21.841
x2          1.656e+05   1443.413    114.754      0.000    1.63e+05    1.68e+05
x3          1.207e+05   1605.160     75.170      0.000    1.18e+05    1.24e+05
x4          1651.1391   1308.671      1.262      0.207    -914.431    4216.709
x5            15.2007      0.144    105.393      0.000      14.918      15.483
==============================================================================
Omnibus:                        5.580   Durbin-Watson:                   2.005
Prob(Omnibus):                  0.061   Jarque-Bera (JB):                4.959
Skew:                           0.011   Prob(JB):                       0.0838
Kurtosis:                       2.847   Cond. No.                     9.40e+05
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 9.4e+05. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [ ]:
### Linear Regression in Scikit Library

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn import metrics

In [ ]:
data.head()

avg_income  avg_house_age  ...  area_population         price
0  79545.458574       5.682861  ...     23086.800503  1.059034e+06
1  79248.642455       6.002900  ...     40173.072174  1.505891e+06
2  61287.067179       5.865890  ...     36882.159400  1.058988e+06
3  63345.240046       7.188236  ...     34310.242831  1.260617e+06
4  59982.197226       5.040555  ...     26354.109472  6.309435e+05

[5 rows x 6 columns]

In [ ]:
X = data[['avg_income','avg_house_age','avg_number_rooms','avg_number_bedrooms','area_population']]

In [ ]:
Y = data['price']

In [ ]:
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size = 0.2, random_state = 0)

In [ ]:
Y_train.head()

2913    1.616937e+06
3275    1.881075e+06
775     1.930344e+06
217     8.859206e+05
1245    1.266210e+06
Name: price, dtype: float64

In [ ]:
X_train.head()

avg_income  avg_house_age  ...  avg_number_bedrooms  area_population
2913  80196.242251       6.675697  ...                 3.17     48694.864144
3275  74130.606324       6.919663  ...                 3.24     49958.580994
775   67384.000373       7.224281  ...                 6.43     48918.055356
217   59569.537340       6.279537  ...                 4.24     31294.652460
1245  58385.215373       7.588559  ...                 2.30     41930.375009

[5 rows x 5 columns]

In [ ]:
regressor = LinearRegression()

In [ ]:
regressor.fit(X_train,Y_train)

LinearRegression()

In [ ]:
regressor.intercept_

-2646630.5310569573

In [ ]:
regressor.coef_

array([2.16604083e+01, 1.65809651e+05, 1.20329408e+05, 2.19309558e+03,
       1.52858855e+01])

In [ ]:
Y_pred = regressor.predict(X_test)

In [ ]:
compare_dataset= pd.DataFrame({'Actual': Y_test,'Predicted': Y_pred})

In [ ]:
print("MAE: ",metrics.mean_absolute_error(compare_dataset.Actual,compare_dataset.Predicted))

MAE:  82657.9460589282


In [ ]:
print("MSE: ",metrics.mean_squared_error(compare_dataset.Actual,compare_dataset.Predicted))

MSE:  10549721686.161528


In [ ]:
print("RMSE: ",np.sqrt(metrics.mean_absolute_error(compare_dataset.Actual,compare_dataset.Predicted)))

RMSE:  287.50294965257


In [ ]:
print("R-squared: ",metrics.r2_score(compare_dataset.Actual,compare_dataset.Predicted))

R-squared:  0.9146454505137888
